api:
  replicaCount: 2
  image:
    tag: "0.9.3"
  ingress:
    enabled: false

frontend:
  replicaCount: 2
  image:
    tag: "1.0.0"
  ingress:
    enabled: false

worker:
  replicaCount: 1
  image:
    tag: "1.0.0"
