replicaCount: 2
image:
  repository: node
  pullPolicy: IfNotPresent
  tag: "18-alpine"
service:
  type: ClusterIP
  port: 3000
ingress:
  enabled: false
  className: nginx
  host: api.example.com
  annotations: {}
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
